version: '3.7'

services:
  webapp:
    image: python:3.9-slim
    container_name: webapp
    volumes:
      - ./webapp:/app
    working_dir: /app
    # command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "5000:5000"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DB=test_db
    depends_on:
      - clickhouse
    build:
      context: webapp
      dockerfile: Dockerfile
    # entrypoint: ["/app/docker-entrypoint.sh"]

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    # users: 
    #   enabled: true
    #   user: 
    #   - name: "admin"
    #     config:
    #       password: "d7dbeFZG8SovV86v22"

  superset:
    user: root
    image: apache/superset:4.0.1-py310
    container_name: superset
    environment:
      # - SUPERSET_LOAD_EXAMPLES=yes
      - SUPERSET_SECRET_KEY=admin
      # - SQLALCHEMY_DATABASE_URI = 'sqlite:///db.sqlite'
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=admin
    volumes:
      - ./superset:/app
    ports:
      - "8088:8088"
    depends_on:
      - clickhouse
    entrypoint: ["/app/docker-entrypoint.sh"]

volumes:
  clickhouse_data:
  superset:
